/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_billionav_CrashMaker */
#include "CrashMaker.h"
#include <stdio.h>

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_billionav_CrashMaker
 * Method:    doCrash
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_billionav_supsystest_CrashMaker_doCrash
  (JNIEnv *, jclass) {
	int *a=0;
	for (int i=0; i<100; i++){
		a[i]=100;
	}
}

JNIEXPORT void JNICALL Java_com_billionav_supsystest_CrashMaker_dolibcCrash
  (JNIEnv *, jclass) {
	sprintf("%s,%d",0);
}


#ifdef __cplusplus
}
#endif
