/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_billionav_CrashMaker */

#ifndef _Included_com_billionav_CrashMaker
#define _Included_com_billionav_CrashMaker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_billionav_CrashMaker
 * Method:    doCrash
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_billionav_supsystest_CrashMaker_doCrash
  (JNIEnv *, jclass);

/*
 * Class:     com_billionav_CrashMaker
 * Method:    dolibcCrash
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_billionav_supsystest_CrashMaker_dolibcCrash
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
