/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_billionav_supsys_jniCErrorRegister */

#ifndef _Included_com_billionav_supsys_jniCErrorRegister
#define _Included_com_billionav_supsys_jniCErrorRegister
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_billionav_supsys_jniCErrorRegister
 * Method:    registSignal
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_billionav_supsys_jniCErrorRegister_registSignal
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
